from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import TYPE_CHECKING, Final

from codescent.engine.rules.model import CodeHealthFinding, FindingSpec, build_finding

if TYPE_CHECKING:
    from codescent.engine.parsers.python import ParsedPythonFile

TODO_CLUSTER_SIZE: Final = 2
DUPLICATE_LITERAL_COUNT: Final = 2
MIN_LITERAL_LENGTH: Final = 4


def secondary_findings(
    parsed: ParsedPythonFile,
    lines: list[str],
    indexed_paths: set[str],
) -> tuple[CodeHealthFinding, ...]:
    findings: list[CodeHealthFinding] = []
    findings.extend(_todo_cluster(parsed, lines))
    findings.extend(_duplicate_literals(parsed, lines))
    findings.extend(_missing_nearby_test(parsed, indexed_paths))
    findings.extend(_slop_candidate(parsed, lines))
    return tuple(findings)


def _todo_cluster(
    parsed: ParsedPythonFile,
    lines: list[str],
) -> tuple[CodeHealthFinding, ...]:
    count = sum(1 for line in lines if _todo_marker(line))
    if count < TODO_CLUSTER_SIZE:
        return ()
    return (
        build_finding(
            FindingSpec(
                rule_id="typescript.todo_cluster",
                title="TODO/FIXME/HACK cluster",
                message=f"{parsed.path} contains {count} TODO-like markers.",
                file_path=parsed.path,
                symbol=None,
                severity="info",
                confidence=0.8,
                evidence={"count": count, "threshold": TODO_CLUSTER_SIZE},
                suggested_action="Resolve or split TODOs into tracked work.",
            ),
        ),
    )


def _duplicate_literals(
    parsed: ParsedPythonFile,
    lines: list[str],
) -> tuple[CodeHealthFinding, ...]:
    literals = Counter(
        match
        for line in lines
        for match in _quoted_literals(line)
        if len(match) > MIN_LITERAL_LENGTH
    )
    return tuple(
        build_finding(
            FindingSpec(
                rule_id="typescript.duplicate_literal",
                title="Duplicate literal string",
                message=f"{parsed.path} repeats a literal {count} times.",
                file_path=parsed.path,
                symbol=None,
                severity="info",
                confidence=0.7,
                evidence={"literal": literal, "count": count},
                suggested_action="Name the repeated literal once and reuse it.",
            ),
        )
        for literal, count in literals.items()
        if count >= DUPLICATE_LITERAL_COUNT
    )


def _missing_nearby_test(
    parsed: ParsedPythonFile,
    indexed_paths: set[str],
) -> tuple[CodeHealthFinding, ...]:
    if parsed.is_test or not parsed.symbols:
        return ()
    expected = _expected_test(parsed.path)
    if expected in indexed_paths:
        return ()
    return (
        build_finding(
            FindingSpec(
                rule_id="typescript.missing_nearby_test",
                title="Missing nearby test candidate",
                message=f"{parsed.path} has symbols but no nearby {expected}.",
                file_path=parsed.path,
                symbol=parsed.symbols[0].qualified_name,
                severity="info",
                confidence=0.65,
                evidence={"expected_test": expected},
                suggested_action="Add or link a focused nearby test for this module.",
            ),
        ),
    )


def _slop_candidate(
    parsed: ParsedPythonFile,
    lines: list[str],
) -> tuple[CodeHealthFinding, ...]:
    marker_count = sum(1 for line in lines if _slop_marker(line))
    if marker_count == 0:
        return ()
    return (
        build_finding(
            FindingSpec(
                rule_id="typescript.suspicious_slop_candidate",
                title="Suspicious generated/slop pattern candidate",
                message=f"{parsed.path} has {marker_count} suspicious markers.",
                file_path=parsed.path,
                symbol=None,
                severity="info",
                confidence=0.5,
                evidence={"marker_count": marker_count},
                suggested_action="Review whether this code is intentional.",
            ),
        ),
    )


def _expected_test(path: str) -> str:
    file_name = Path(path).name
    stem, suffix = file_name.rsplit(".", maxsplit=1)
    return f"tests/{stem}.test.{suffix}"


def _quoted_literals(line: str) -> tuple[str, ...]:
    parts = line.replace('"', "'").split("'")
    return tuple(parts[index] for index in range(1, len(parts), 2))


def _todo_marker(line: str) -> bool:
    folded = line.upper()
    return "TODO" in folded or "FIXME" in folded or "HACK" in folded


def _slop_marker(line: str) -> bool:
    folded = line.lower()
    return "generated by" in folded or "placeholder" in folded
