"""Characterization-test skeleton generator.

Given a target symbol, emit a RED, runnable pytest skeleton that imports the
target and leaves clearly-marked TODO placeholders. The skeleton never asserts
a fake green: the placeholder raises ``NotImplementedError`` so pytest collects
the test but it cannot pass until a human pins the current behavior.
Deterministic, bounded, no network, read-only.
"""

from __future__ import annotations

import ast
import keyword
from dataclasses import dataclass

__all__ = [
    "CharacterizationScaffold",
    "build_characterization_scaffold",
    "module_path_from_file",
]

# ponytail: one short test function; the skeleton is bounded by construction.

_TEMPLATE = '''\
"""Characterization test scaffold for {target}.

Generated by CodeScent's suggest_tests scaffold. This file PINS the current
behavior of the target before a refactor. It is intentionally RED: the
placeholder below raises until you replace it with a real assertion on the
behavior you observe today. Do not commit the placeholder as-is.
"""


{import_line}


def {test_name}() -> None:
    # TODO: build representative inputs for {target}.
    # TODO: call {call_hint} and capture the result.
    # TODO: replace the raise below with an assertion that pins the OBSERVED
    #       current behavior, e.g. assert result == <value you saw>.
    raise NotImplementedError(
        "TODO: characterize {target} before refactoring "
        "(placeholder, not a real assertion)."
    )
'''


@dataclass(frozen=True, slots=True)
class CharacterizationScaffold:
    language: str
    module: str
    symbol: str
    test_name: str
    filename: str
    code: str
    notes: tuple[str, ...]


def module_path_from_file(file_path: str) -> str:
    """Derive a dotted import path from a repo-relative ``.py`` path.

    Mirrors the parser's module convention: drop a leading ``src`` segment and
    ``__init__`` packages, strip ``.py``, join the rest with dots.
    """
    posix = file_path.replace("\\", "/").removesuffix(".py")
    parts = [part for part in posix.split("/") if part and part != "__init__"]
    if parts[:1] == ["src"]:
        parts = parts[1:]
    return ".".join(parts)


def build_characterization_scaffold(
    *,
    file_path: str,
    qualified_symbols: tuple[str, ...] = (),
) -> CharacterizationScaffold:
    """Build a RED characterization-test skeleton for a finding's target.

    The first resolvable top-level symbol is imported and called with
    placeholders; if none resolves, the module itself is imported. The output is
    validated with :func:`ast.parse` so the generator never emits code that
    fails collection for a syntax reason.
    """
    module = module_path_from_file(file_path)
    symbol = ""
    if qualified_symbols:
        symbol = _importable_symbol(module, qualified_symbols[0])
    code, test_name, resolved_symbol, notes = _render(module, symbol)
    _ = ast.parse(code)  # honesty guard: never emit unparsable code
    return CharacterizationScaffold(
        language="python",
        module=module,
        symbol=resolved_symbol,
        test_name=test_name,
        filename=f"{test_name}.py",
        code=code,
        notes=notes,
    )


def _importable_symbol(module: str, qualified_name: str) -> str:
    """Top-level importable name for a (possibly dotted) qualified symbol."""
    remainder = qualified_name
    prefix = f"{module}."
    if module and qualified_name.startswith(prefix):
        remainder = qualified_name[len(prefix) :]
    return remainder.split(".", 1)[0]


def _is_dotted_identifier(value: str) -> bool:
    return bool(value) and all(
        part.isidentifier() and not keyword.iskeyword(part) for part in value.split(".")
    )


def _is_identifier(value: str) -> bool:
    return value.isidentifier() and not keyword.iskeyword(value)


def _render(module: str, symbol: str) -> tuple[str, str, str, tuple[str, ...]]:
    notes: list[str] = []
    valid_module = _is_dotted_identifier(module)
    valid_symbol = _is_identifier(symbol)

    if valid_module and valid_symbol:
        import_line = f"from {module} import {symbol}"
        target = symbol
        resolved_symbol = symbol
        slug = symbol
        call_hint = f"{symbol}(...)"
    elif valid_module:
        import_line = f"import {module}"
        target = module
        resolved_symbol = ""
        slug = module.replace(".", "_")
        call_hint = f"{module}.<callable>(...)"
        notes.append(
            "no importable symbol resolved from the finding; targeting the module",
        )
    else:
        import_line = "# TODO: import the target under test"
        target = "the target"
        resolved_symbol = ""
        slug = "target"
        call_hint = "the_target(...)"
        notes.append(
            "could not derive an import path; replace the import placeholder",
        )

    test_name = f"test_{slug}_characterization"
    code = _TEMPLATE.format(
        target=target,
        import_line=import_line,
        test_name=test_name,
        call_hint=call_hint,
    )
    return code, test_name, resolved_symbol, tuple(notes)
